import assert from 'node:assert/strict';
import {build,defaults,zAt,clampDepth} from '../dist/geometry.js';
function ray(mesh,x,y){const zs=[];for(const f of mesh.f){const[a,b,c]=f.map(i=>mesh.v[i]),den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-9)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,v=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den;if(u>=-1e-7&&v>=-1e-7&&u+v<=1+1e-7)zs.push(u*a[2]+v*b[2]+(1-u-v)*c[2]);}return zs.sort((a,b)=>a-b).filter((z,i,a)=>!i||z-a[i-1]>1e-5);}
for(const cfg of [{},{diameter:180,fd:.25,thickness:1.6},{diameter:800,rearStyle:1},{diameter:600,rows:3,jointClearance:.4}]){
 const m=build({...defaults,...cfg}),root=m.parts.find(p=>p.id==='panel-1'),hub=m.parts.find(p=>p.id==='hub-rear'),cap=m.parts.find(p=>p.id==='hub-clamp'),T=clampDepth(m.p),B=T+Math.max(3,m.p.thickness);
 for(const part of m.parts){for(const h of part.spec.holes){const x=h.r*Math.cos(h.a),y=h.r*Math.sin(h.a);for(const angle of [0,Math.PI/4,Math.PI/2])assert.equal(ray(part.mesh,x+2*Math.cos(angle),y+2*Math.sin(angle)).length,0,part.id+': bore must clear a round shaft');}}
 for(const part of m.parts.filter(p=>p.spec.nuts)){for(let i=0;i<part.spec.holes.length;i++){const h=part.spec.holes[i],a=h.a,x=h.r*Math.cos(a),y=h.r*Math.sin(a),seat=part.spec.nutSeats[i],inside=ray(part.mesh,x+(part.spec.nuts[i].af/2-.2)*Math.cos(a),y+(part.spec.nuts[i].af/2-.2)*Math.sin(a));assert(inside.length>=2);assert(Math.abs(inside[0]-seat)<.002,part.id+': nut bearing face is horizontal');const outside=ray(part.mesh,x+(part.spec.nuts[i].af/2+.2)*Math.cos(a),y+(part.spec.nuts[i].af/2+.2)*Math.sin(a));assert(outside[0]<seat-3.1,part.id+': hex wall captures nut');assert(inside.at(-1)-inside[0]>1.98,part.id+': material above nut');}}
 const r=46,a=Math.min(.08,Math.PI/m.layout.n*.7),x=r*Math.cos(a),y=r*Math.sin(a),pr=ray(root.mesh,x,y),hr=ray(hub.mesh,x,y);assert(Math.abs(pr[0]-(zAt(r,m.p)-B-2))<.03,'Root lip depth');assert(Math.abs(pr[0]-hr.at(-1)-.2)<.03,'Groove axial clearance');const notch=ray(root.mesh,r,0),tooth=ray(hub.mesh,r,0);assert(Math.abs(notch[0]-(zAt(r,m.p)-B))<.03,'Indexing notch');assert(Math.abs(notch[0]-tooth.at(-1)-.2)<.03,'Indexing tooth fits notch');
 const pilot=ray(cap.mesh,40,0),channel=ray(hub.mesh,40,0);assert(Math.abs(pilot[0]-channel.at(-1)-.2)<.04,'Concentric pilot enters hub groove');const c=ray(cap.mesh,58,0),p=ray(root.mesh,58,0);assert(Math.abs(c.at(-1)-zAt(58,m.p))<.03,'Cap face is parabolic');assert(Math.abs(c[0]-p.at(-1))<.03,'Cap captures root shoulder flush');
 for(let i=0;i<cap.spec.heads.length;i++){const h=cap.spec.heads[i],v=ray(cap.mesh,(h.r+3)*Math.cos(h.a),(h.r+3)*Math.sin(h.a));assert(Math.abs(v.at(-1)-cap.spec.headSeats[i])<.002,'Flat recessed head seat');assert(cap.spec.headSeats[i]+2.2<zAt(h.r-4,m.p),'Low profile head remains below dish');assert(v.at(-1)-v[0]>=1.95,'Head seat has supporting wall');}
 console.log('PASS round bores, captured nuts, keyed root groove and flush cap',cfg);
}
