"""Render invariant fittings using OpenSCAD; embed welded meshes for offline use."""
import json, struct, subprocess, tempfile
from pathlib import Path
root=Path(__file__).resolve().parents[1]
meshes={}
for name in ['clevis','rod-end','carrier-3','carrier-4']:
    with tempfile.TemporaryDirectory() as td:
        path=Path(td)/'part.stl'
        subprocess.run(['openscad','--export-format','binstl','-o',str(path),'-D',f'part="{name}"',str(root/'cad/feed-fittings.scad')],check=True)
        data=path.read_bytes(); nv=struct.unpack_from('<I',data,80)[0]; vertices=[]; faces=[]; ids={}
        for i in range(nv):
            vals=struct.unpack_from('<12fH',data,84+50*i); f=[]
            for j in range(3):
                v=tuple(round(x,5) for x in vals[3+j*3:6+j*3])
                if v not in ids: ids[v]=len(vertices);vertices.append(v)
                f.append(ids[v])
            faces.append(f)
        meshes[name]={'v':vertices,'f':faces}
(root/'dist/feed-meshes.js').write_text('// Generated by scripts/build-feed-templates.py; do not hand edit.\nexport const feedMeshes='+json.dumps(meshes,separators=(',',':'))+';\n')
