const fs=require('fs'),assert=require('assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const errors=[],consoleCapture=new VirtualConsole();consoleCapture.on('jsdomError',e=>{if(!/getContext|navigation/.test(e.message))errors.push(e.message)});
const html=fs.readFileSync(require('path').join(__dirname,'../dist/petal-offline.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'http://localhost/',virtualConsole:consoleCapture,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLCanvasElement.prototype.getContext=()=>null;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};}});
const w=dom.window,d=w.document,wait=()=>new Promise(r=>setTimeout(r,700));
(async()=>{await wait();assert.equal(errors.length,0,errors.join("\n"));assert.equal(d.getElementById('error').hidden,true);assert(d.getElementById('structuralRibs').checked);assert(d.getElementById('supports').checked);assert.equal(d.getElementById('perforate').checked,false);assert(d.getElementById('print-result').textContent.includes('45°'));
for(const mode of ['1','2','0']){const field=d.getElementById('fastenerStyle');field.value=mode;field.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();assert.equal(d.getElementById('error').hidden,true);d.getElementById('guide-toggle').click();assert(d.getElementById('guide').open);const text=d.getElementById('guide-content').textContent;assert(text.includes(mode==='1'?'FRONT hex':mode==='2'?'blind inserts':'FRONT into rear'));d.getElementById('guide-close').click();assert(!d.getElementById('guide').open);}
const nuts=d.getElementById('nutClearance');nuts.value='.3';nuts.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();assert.equal(d.getElementById('jointClearance').value,'0.2');assert(d.getElementById('guide-content').textContent.includes('7.60'));
d.getElementById('packPlates').click();await wait();assert(d.getElementById('packing-result').textContent.includes('shared beds'));d.getElementById('reset').click();await wait();assert(!d.getElementById('packPlates').checked);assert.equal(d.getElementById('nutClearance').value,'0.2');for(const mode of ['1','2']){const f=d.getElementById('feedMode');f.value=mode;f.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();assert.equal(d.getElementById('error').hidden,true,d.getElementById('error').textContent);assert(d.getElementById('feed-result').textContent.includes('rods'));assert(d.getElementById('guide-content').textContent.includes('Rod support'));}const setField=async(id,value)=>{const x=d.getElementById(id);x.value=String(value);x.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();};
await setField('frequencyGHz',15);assert(d.getElementById('error').hidden);const firstCut=d.getElementById('feed-result').textContent;assert(d.getElementById('secondaryPosition').disabled);
await setField('frequencyGHz',20);assert(d.getElementById('error').hidden);assert.notEqual(d.getElementById('feed-result').textContent,firstCut);
await setField('frequencyGHz',2.4);assert(!d.getElementById('error').hidden);assert(d.getElementById('error').textContent.includes('25%'));
await setField('feedMode',1);assert(d.getElementById('error').hidden);await setField('rodDiameter',0);assert(d.getElementById('error').hidden);
await setField('frequencyGHz',20);await setField('phaseOffset',.2);await setField('phaseUnits',1);assert(d.getElementById('error').hidden);assert(d.getElementById('feed-result').textContent.includes('puck z 165.0'));assert(d.getElementById('feed-result').textContent.includes('λ 14.99'));
await setField('frequencyGHz',0);assert(!d.getElementById('error').hidden);await setField('phaseUnits',0);assert(d.getElementById('error').hidden);
const legs=d.getElementById('feedLegs');legs.value='4';legs.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();assert.equal(d.getElementById('error').hidden,true);assert(d.getElementById('feed-result').textContent.includes('4 rods'));d.getElementById('reset').click();await wait();assert.equal(d.getElementById('feedMode').value,'0');assert.equal(errors.length,0,errors.join('\n'));console.log('PASS offline app startup, controls, all three live instruction modes, independent tolerances, packing and reset (DOM only; no WebGL renderer)');w.close();})().catch(e=>{console.error(e);w.close();process.exitCode=1;});
