import fs from 'node:fs';
import crypto from 'node:crypto';
import {build} from 'esbuild';
import {INTERFACE_REVISION} from '../dist/interface.js';
const version='5.3',offline=`petal-${version}-offline.html`,hash=crypto.createHash('sha256');
for(const name of fs.readdirSync('dist').filter(x=>/\.(js|css|html)$/.test(x)&&!['app.bundle.js','version.js','petal-offline.html',offline].includes(x)).sort())hash.update(name).update(fs.readFileSync('dist/'+name));
hash.update(fs.readFileSync('package-lock.json')).update(fs.readFileSync('scripts/pack-offline.mjs'));
const id=hash.digest('hex').slice(0,12);
fs.writeFileSync('dist/version.js',`// Generated by scripts/pack-offline.mjs.\nexport const VERSION='${version}';\nexport const BUILD_ID='${id}';\n`);
const wasm=fs.readFileSync('node_modules/manifold-3d/manifold.wasm').toString('base64');
const options={bundle:true,format:'esm',platform:'browser',external:['node:module','canvg','html2canvas','dompurify'],write:false,minify:true,define:{'import.meta.url':'"https://petal.invalid/app.js"'}};
// The geometry engine (WASM kernel, exports, PDF) runs in a Web Worker. It is embedded as a string so the hosted
// page and the single offline file both start it from a Blob URL; app.js runs it on the page if workers fail.
const engine=(await build({...options,entryPoints:['dist/engine.js']})).outputFiles[0].text;
const engineSource=`globalThis.PETAL_WASM_BASE64="${wasm}";\n(async()=>{${engine}\n})().catch(e=>{(globalThis.__PETAL_ENGINE_PORT__||self).postMessage({op:'fatal',error:String(e&&e.message||e)});});`;
const app=(await build({...options,entryPoints:['dist/app.js']})).outputFiles[0].text;
const notice=fs.readFileSync('THIRD-PARTY-NOTICES.md','utf8').replaceAll('*/','* /');
const code=`/* ${notice} */\nglobalThis.PETAL_ENGINE_SOURCE=${JSON.stringify(engineSource)};\n(async()=>{${app}\n})().catch(e=>{const el=document.getElementById('error');el.hidden=false;el.textContent='Could not start PETAL: '+e.message;console.error(e);});`;
fs.writeFileSync('dist/app.bundle.js',code);
const source=fs.readFileSync('dist/index.html','utf8');
const html=source.replace('<link rel="stylesheet" href="style.css">',()=>`<style>${fs.readFileSync('dist/style.css','utf8')}</style>`).replace('<script src="app.bundle.js"></script>',()=>`<script>${code.replace(/<\/script/gi,'<\\/script')}</script>`).replace('href="./" aria-label="PETAL home"','href="#" aria-label="PETAL home"').replace(/<a class="button quiet" href="petal-[^"]+" download>.*?<\/a>/,`<span class="button quiet">Offline app</span>`);
if(html===source||!html.includes('<style>')||!html.includes('PETAL_ENGINE_SOURCE'))throw Error('Offline packing did not inline the page assets.');
fs.writeFileSync('dist/'+offline,html);
// The stable old filename now redirects instead of retaining another full copy.
fs.writeFileSync('dist/petal-offline.html',`<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${offline}"><title>PETAL ${version}</title><a href="${offline}">Download PETAL ${version} offline</a>\n`);
const files=Object.fromEntries(['index.html','app.bundle.js','style.css',offline,'petal-offline.html'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync('dist/'+name)).digest('hex')]));
fs.writeFileSync('dist/BUILD.json',JSON.stringify({version,build:id,interface:INTERFACE_REVISION,offline_file:offline,files},null,2)+'\n');
console.log(`PETAL ${version} build ${id}: offline ${Buffer.byteLength(html)} bytes; engine ${Math.round(engineSource.length/1024)} KB, page ${Math.round(app.length/1024)} KB.`);
